import xbmc, xbmcgui
from resources.lib import ___, __
pDialog = xbmcgui.DialogProgress()
d = xbmcgui.Dialog()
pDialog.create('VHS PVR Changer', '')
pDialog.update(0, 'Pokrećem')
path = ___.pvr()
pDialog.update(10, 'Biram listu')
__.STR()
pDialog.update(20, 'Lista programa je osvježena')
pDialog.update(30, 'Resetiram PVR klijent')
xbmc.sleep(500)
pDialog.update(50, 'Resetiram PVR klijent')
__.disable_pvr()
pDialog.update(70, 'Resetiram PVR klijent')
xbmc.sleep(2000)
pDialog.update(90, 'Resetiram PVR klijent')
__.enable_pvr()
pDialog.update(100, 'PVR klijent resetiran')
ok1 = d.notification('VHS PVR Changer', 'PVR klijent je osvježen. Molimo pričekajte', xbmcgui.NOTIFICATION_INFO, 15000)